### ISSUE TITLE
weird caps lock behavoir

### ISSUE THREAD

**Issue by lkyhfx** [ShadowPower/xiaoxin-air13-iwl-hackintosh#2]

**Comment by lkyhfx** [comment]
按下caps lock, 大写灯亮，但是没有切换输入法。在设置里交换control 和 caps lock后，第一次按下caps lock，大写灯亮，然后一直处在大写模式，再也跳不出去。
但是外接usb机械键盘没有问题，有解决办法嘛😂

**Comment by ShadowPower** [comment]
试了试，好像确实有这样的问题，按了之后好像会进入锁定Control按键的状态……
目前没找到什么好办法😰

**Comment by lkyhfx** [comment]
问题解决啦，得换一下kext https://github.com/acidanthera/bugtracker/issues/435
